import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
// import Header from "./../src/frontend/components/header/header";
// import Header from "./../components/header";
import Main from "../components/main";
import LandingCards from "../assets/landing-cards.svg";
import cardtick from "../assets/card-tick.svg";
import Chartsquare from "../assets/chart-square.svg";

export default function Home() {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.js</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
    <>
      {/* <Header /> */}
      {/* <Main /> */}
      <div className="max-w-6xl flex flex-col lg:flex-row mx-auto mt-8 px-8 mb-12">
        <div
          className="w-1/2 pt-9"
          // style={{ border: "1px solid blue" }}
        >
          <h1 className="font-bold text-4xl">
            DISCOVER, AND COLLECT DIGITAL ART NFTS{" "}
          </h1>
          <p
            className="text-darkGrey font-normal max-w-sm text-lg mt-4"
            // style={{ border: "1px solid red" }}
          >
            Digital marketplace for crypto collectibles and non-fungible tokens
            (NFTs). Buy, Sell, and discover exclusive digital assets.
          </p>
          <button className="rounded-3xl bg-navyBlue text-white border-navyBlue px-6 py-2 text-base mt-9">
            Explore Now
          </button>

          <div className="mt-7 flex gap-5">
            <div className="flex flex-col">
              <span className="font-bold text-4xl">98K+</span>
              <span className="text-darkGrey font-normal text-base">
                Artwork
              </span>
            </div>
            <div className="flex flex-col">
              <span className="font-bold text-4xl">12K+</span>
              <span className="text-darkGrey font-normal text-base">
                Auction
              </span>
            </div>
            <div className="flex flex-col">
              <span className="font-bold text-4xl">15K+</span>
              <span className="text-darkGrey font-normal text-base">
                Artist
              </span>
            </div>
          </div>
        </div>
        <div
          className="w-1/2 flex"
          //  style={{ border: "1px solid green" }}
        >
          <div>
            <Image src={LandingCards} alt="Cards" width={500} />
          </div>
        </div>
      </div>

      <div className="bg-grey py-14 ">
        <div className="max-w-6xl mx-auto px-8 flex gap-5">
          <div className="w-2/5" style={{ border: "1px solid red" }}>
            <h2 className="font-bold text-3xl">
              THE AMAZING NFT ART OF THE WORLD HERE
            </h2>
          </div>
          <div className="w-3/5 flex gap-6">
            <div
              className="w-1/2 flex gap-2 items-start"
              style={{ border: "1px solid blue" }}
            >
              {/* <div>jihu</div> */}
              <Image src={cardtick} alt="Cards" width="50px" height="50px" />

              <div>
                <p className="font-bold text-base mb-1">Fast Transaction</p>
                <p className="text-sm text-darkGrey">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Aliquam etiam viverra tellus imperdiet.
                </p>
              </div>
            </div>
            <div
              className="w-1/2 flex gap-2 items-start"
              style={{ border: "1px solid blue" }}
            >
              <Image src={Chartsquare} alt="Cards" width="50px" height="50px" />

              <div>
                <p className="font-bold text-base mb-1">Growth Transaction</p>
                <p className="text-sm text-darkGrey">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Aliquam etiam viverra tellus
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
